---
title: "Ethics and data"
author: GEOG 30323
date: December 8, 2015
output: 
  revealjs::revealjs_presentation: 
    theme: "white"
    transition: "none"
    highlight: "zenburn"
    center: TRUE
    fig_caption: TRUE
    
---

## Reminders

* Exam 3 due by the  end of the day on __Tuesday, December 15__
* Tucker 002 available from 8:00-10:30 to work on the exam; I'll be there!

---

## Ethics

* Discuss: what does "ethics" mean to you?

---

### Big data

<iframe width="100%" height="600px" frameBorder="0" src="https://a.tiles.mapbox.com/v4/enf.c3a2de35.html?access_token=pk.eyJ1IjoiZW5mIiwiYSI6IkNJek92bnMifQ.xn2_Uj9RkYTGRuCGg4DXZQ"></iframe><figcaption>Map by Eric Fischer, Mapbox</figcaption>

---

### The Ashley Madison hack

<iframe width='100%' height='600' frameborder='0' src='https://tecnilogica.cartodb.com/viz/56e702fe-4693-11e5-8f79-0e853d047bba/embed_map' allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen></iframe>

---

### 'Microtargeting' and elections

> "Nix says his database has between 4,000 and 5,000 data points on every registered voter in the U.S. — from where you shop to websites you’ve visited, cars you’ve driven, magazines you’ve subscribed to and your all-important voter registration history."

https://www.yahoo.com/politics/neurotic-extroverted-disagreeable-political-campaigns-1291656824504374.html

---

### Terrorism and privacy



> "After the Paris attacks, democratic societies can reasonably ask whether the right to remain
anonymous, be it online or travelling around Europe, should remain near-absolute. As long as
there is proper democratic oversight of those handling the data, Europeans will have to give up
some anonymity to preserve the liberty and security that matter." [(From _The Economist_)](http://www.economist.com/news/briefing/21679266-how-balance-security-privacy-after-paris-attacks-terrorist-data?fsrc=scn/tw/te/pe/ed/theterroristinthedata) 

What do you think? 








<style>

.reveal section img {
  background:none; 
  border:none; 
  box-shadow:none;
  }

h3 {



}
  
</style>

